Implement hourly time resolution
StatEngine/shiftly pull request #48
Opened 2020-11-05 23:48 UTC by saltaverde

Description from first commit pasted here for convenience:

```
Change implementation to use hourly time resolution

The initial problem was that some departments have special shifts on
leap year days and these shifts are sometimes of different length than
24 hours. Namely, Delaware, OH has three 8-hour shifts on leap days.

The existing shift patterns were based on the assumption of a 24 hour
period per pattern character. These changes allow for a variable shift
duration via the `shiftDuration` parameter.
```

Closes https://github.com/StatEngine/shiftly/issues/18

2020-11-19 21:54 UTC, richard3d requested changes
See comment regarding DST. Can we also get an update on the Readme regarding usage and how to account for any things to be aware of in the parameters such as the new `shiftDuration`?

2020-11-19 21:54 UTC, richard3d commented on src/index.js
> +    if (this.patternStart.isDST() !== momentDate.isDST()) {
I'm not sure we can trust this for all departments. For instance, Any department in Hawaii or Arizona will not recognize DST period. Thoughts?

2020-11-19 22:23 UTC, saltaverde commented on src/index.js
> +    if (this.patternStart.isDST() !== momentDate.isDST()) {
I believe we'd have to specify time zones specifically for those "special" places, like `US/Arizona` as opposed to `US/Mountain`. But should confirm that the behavior is as expected with `moment`

2020-11-21 00:37 UTC, saltaverde commented on src/index.js
> +    if (this.patternStart.isDST() !== momentDate.isDST()) {
It appears to me that `moment` understands that certain timezones do not observe the transition to/from DST, `US/Arizona` being one of them:
```
> var azDstDate = moment.tz('2020-11-01 00:00:00', 'US/Arizona');
undefined
> var azNotDstDate = moment.tz('2020-12-01 00:00:00', 'US/Arizona');
undefined
> azDstDate.isDST()
false
> azNotDstDate.isDST()
false
> var mtDstDate = moment.tz('2020-11-01 00:00:00', 'US/Mountain');
undefined
> var mtNotDstDate = moment.tz('2020-12-01 00:00:00', 'US/Mountain');
undefined
> mtDstDate.isDST();
true
> mtNotDstDate.isDST();
false
```
So, I think we're good.

2020-11-24 22:21 UTC, merged